### PR TITLE
Expendable should be expandable

### PR DESCRIPTION
**Pull request by Mihaiii**
Issue #9

Guys, don't take this the wrong way.
I know what you want, I'm just not sure how you want it.
So I just come up with the simplest solution that works.

Let me know if you want that issue to be solved in another way.

### CODE REVIEW

**Comment by warpech** [comment]
@tomalec ping

**Comment by tomalec** [comment]
You can listen to `slotchanged` event 
https://dom.spec.whatwg.org/#mutation-observers : 
> For each slot slot in signalList, in order, fire an event named slotchange, with its bubbles attribute set to true, at slot.

**Comment by warpech** [comment]
So the MutationObserver is the only option for having a live deprecation notice. Isn't this an overkill? I think that it is not worth implementing, I would merge this PR as is.

**Comment by tomalec** [comment]
You don't need a mutation observer, please check my commit. It's just an event.

BTW, I believe, in most of the cases `attachedCallback` should be enough.

**Comment by warpech** [comment]
Wow, I was super confused by this being defined in the "Mutation observers" section of the spec.

Strange that they decided to have a DOM event for this one thing!

**Comment by tomalec** [comment]
I think it's exremely important to have this.

https://hayato.io/2016/shadowdomv1/#events-to-react-the-change-of-distributions

**Comment by warpech** [comment]
Thanks. @Mihaiii can you review and merge if you agree?

**Pull request merged**
